[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miclustering"
version = "0.1.0"
description = "A Multi-Instance Learning Clustering library"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["multi-instance learning", "clustering", "MIL", "machine learning"]
license = { file = "LICENSE" }
authors = [
  { name="Andres", email="andresmors.jr@gmail.com" },
]
dependencies = [
    "numpy>=1.20.0",
    "scipy>=1.7.0",
    "scikit-learn>=1.0.0",
    "liac-arff>=2.5.0",
    "pandas>=1.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
]

[project.urls]
"Homepage" = "https://github.com/Andmo2004/MIClustering"
"Documentation" = "https://github.com/Andmo2004/MIClustering#readme"

[tool.setuptools.packages.find]
where = ["src"]